services:
  exchanger:
    environment:
      CONSUL_ADDRESS: consul:8500
    depends_on:
      - consul

  wallet:
    environment:
      CONSUL_ADDRESS: consul:8500
    depends_on:
      - consul

  consul:
    image: hashicorp/consul:1.20
    ports:
      - "127.0.0.1:8500:8500" # Web UI
      - "127.0.0.1:8600:8600/udp" # DNS
    command: >
      sh -c "if [ \"$ENV\" = 'development' ]; then
               exec consul agent -dev -client=0.0.0.0;
             else
               exec consul agent -server -bootstrap-expect=1 -client=0.0.0.0;
             fi"
    volumes:
      - consul_data:/consul/data

volumes:
  consul_data: